### ISSUE TITLE
verify presentation should take the full revocation status list and not a rev reg entry

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/anoncreds-rs#74]
Right now the verify presentation method takes a list called `RevocationEntries`. This is not up-to-date with the specification and it should take the new `RevocationStatusList`. 

## Tasks

- [ ] Update the `verifier::verify_presentation` method to verify revocation based on the status list. (@whalelephant)
- [ ] Update the FFI layer to supply a revocation status list. 
- [ ] ~~Make sure the tests in Node.js are working when this is fixed in the FFI layer (separate issue #75 )~~
- [ ] ~~Make sure the tests in Python are working when this is fixed in the FFI layer (separate issue #76)~~

@whalelephant I can pick up the FFI layer and FFI tests, but I am not aware of the changes need to be made for `verify_presentation` to verify with the new status list.
